// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Scalable_Web.Data;

namespace Scalable_Web.Migrations
{
    [DbContext(typeof(Scaleble_Web_Context))]
    partial class Scaleble_Web_ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Scalable_Web.Models.Difference", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<byte[]>("Left")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("Right")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.ToTable("Differences");
                });
#pragma warning restore 612, 618
        }
    }
}
